export const cards = [
  {
    id: 0,
    title: "some title",
    category: "action",
    image: "/images/categories/2.jpg",
  },
  {
    id: 1,
    title: "some title",
    category: "sci-fi",
    image: "/images/categories/1.jpg",
  },
  {
    id: 2,
    title: "some title",
    category: "fantasy",
    image: "/images/categories/3.jpg",
  },
  {
    id: 3,
    title: "some title",
    category: "romance",
    image: "/images/categories/4.jpg",
  },
  {
    id: 4,
    title: "some title",
    category: "comedy",
    image: "/images/categories/5.jpg",
  },
  {
    id: 5,
    title: "some title",
    category: "crime",
    image: "/images/categories/6.jpg",
  },
  {
    id: 6,
    title: "some title",
    category: "mystery",
    image: "/images/categories/7.jpg",
  },
  {
    id: 7,
    title: "some title",
    category: "holiday",
    image: "/images/categories/8.jpg",
  },
  {
    id: 8,
    title: "some title",
    category: "horror",
    image: "/images/categories/9.jpg",
  },
];

export const books = [
  {
    id: 0,
    title: "some title",
    category: "comedy",
    image: "/images/romance.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 1,
    title: "some title",
    category: "comedy",
    image: "/images/action.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 2,
    title: "some title",
    category: "comedy",
    image: "/images/comedy.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 3,
    title: "some title",
    category: "comedy",
    image: "/images/sci-fi.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 4,
    title: "some title",
    category: "comedy",
    image: "/images/fantasy.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 5,
    title: "some title",
    category: "comedy",
    image: "/images/romance.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
  {
    id: 6,
    title: "some title",
    category: "comedy",
    image: "/images/action.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
    desc: "some description about book",
    price: 13.99,
    star: 5,
  },
];
