export const cards = [
  {
    id: 0,
    title: "some title",
    category: "some category for the card",
    image: "/images/romance.svg",
  },
  {
    id: 1,
    title: "some title",
    category: "some category for the card",
    image: "/images/action.svg",
  },
  {
    id: 2,
    title: "some title",
    category: "some category for the card",
    image: "/images/comedy.svg",
  },
  {
    id: 3,
    title: "some title",
    category: "some category for the card",
    image: "/images/sci-fi.svg",
  },
  {
    id: 4,
    title: "some title",
    category: "some category for the card",
    image: "/images/fantasy.svg",
  },
  {
    id: 5,
    title: "some title",
    category: "some category for the card",
    image: "/images/romance.svg",
  },
  {
    id: 6,
    title: "some title",
    category: "some category for the card",
    image: "/images/action.svg",
  },
];

export const books = [
  {
    id: 0,
    title: "some title",
    category: "comedy",
    image: "/images/romance.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
  },
  {
    id: 1,
    title: "some title",
    category: "comedy",
    image: "/images/action.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
  },
  {
    id: 2,
    title: "some title",
    category: "comedy",
    image: "/images/comedy.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
  },
  {
    id: 3,
    title: "some title",
    category: "comedy",
    image: "/images/sci-fi.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
  },
  {
    id: 4,
    title: "some title",
    category: "comedy",
    image: "/images/fantasy.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
  },
  {
    id: 5,
    title: "some title",
    category: "comedy",
    image: "/images/romance.svg",
    profilePic: "/images/userf1.png",
    author: "Tania",
  },
  {
    id: 6,
    title: "some title",
    category: "comedy",
    image: "/images/action.svg",
    profilePic: "/images/userm1.png",
    author: "Ricky",
  },
];
